name: 'Start Database'
description: 'Start databases for the test'
inputs:
  postgres:
    description: 'PostgreSQL Database'
    required: false
    default: true
  mysql:
    description: 'MySQL Database'
    required: false
    default: true

# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-id }}

runs:
  using: "composite"
  steps:
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql db: postgres
        postgresql user: postgres
        postgresql password: postgres

    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql root password: mysql
        mysql database: mysql