name: 'Start Database'
description: 'Start databases for the test'

runs:
  using: "composite"
  steps:
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql db: postgres
        postgresql user: postgres
        postgresql password: postgres

    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql root password: mysql
        mysql database: mysql

    # - name: ClickHouse in GitHub Actions
    #   uses: EpicStep/clickhouse-github-action@v1.0.0

    - name: mssql suite
      uses: potatoqualitee/mssqlsuite@v1.1
      with:
        install: sqlengine
        sa-password: Adm1n123
