name: 'Start Database'
description: 'Start databases for the test'

runs:
  using: "composite"
  steps:
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql db: postgres
        postgresql user: postgres
        postgresql password: postgres

    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql root password: mysql
        mysql database: mysql
    
    # - name: ClickHouse Server Action
    #   # You may pin to the exact commit or the version.
    #   # uses: metrico/clickhouse-server-action@2bcff7db46f142a4c31df33512905bbf90b72bc0
    #   uses: metrico/clickhouse-server-action@v1.0.0


    - name: ClickHouse in GitHub Actions
      # You may pin to the exact commit or the version.
      # uses: EpicStep/clickhouse-github-action@1d58245e87a8208d2f9dbf84306b90241bcb4aa3
      uses: EpicStep/clickhouse-github-action@v1.0.0